### USER - Создание нового Юзера
POST http://localhost/api/users/
Content-Type: application/json

{
  "username": "user3",
  "password": "admin123456"
}


### Создать TOKEN для нового Юзера (копируем значение ключа "access")
POST http://localhost/api/auth/jwt/create/
Content-Type: application/json

{
  "username": "user3",
  "password": "admin123456"
}

> {% client.global.set("token", response.body.access); %}


### ДОПОЛНИТЕЛЬНО******************************************************************************

### Проверка данных Юзера
GET http://localhost/api/users/me/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjM4Mzg2LCJpYXQiOjE3MzAxMDIzODYsImp0aSI6ImQ4NjhmMzc4NzZlNzQwMWRiYjlkOTU4OWE0NTJlZWUxIiwidXNlcl9pZCI6NH0.Qm_oG6WGXNkc3MopOQZhl8OJx6yyBWMyHks25_lYGxU

