# Generated by Django 4.2.5 on 2024-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_configurations", "0004_alter_camera_roi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="class_for_pass_round",
            field=models.ManyToManyField(
                blank=True, related_name="rounds", to="admin_configurations.objectclass"
            ),
        ),
        migrations.AlterField(
            model_name="modeldetect",
            name="path",
            field=models.CharField(
                default="/app/models/pt/yolov8x.pt", max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="modeldetect",
            name="task",
            field=models.CharField(
                choices=[("pose", "Pose"), ("detect", "Detect")],
                default="detect",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="modeldetect",
            name="type",
            field=models.CharField(
                choices=[
                    ("model_pose_yolo", "Model Pose Yolo"),
                    ("model_yolo", "Model Yolo"),
                    ("need_skeleton", "Need Skeleton"),
                ],
                default="model_pose_yolo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="objectclass",
            name="text_for_onvif",
            field=models.CharField(default="detected", max_length=50),
        ),
        migrations.AlterField(
            model_name="objectclass",
            name="text_for_telegram",
            field=models.CharField(default="Обнаружен объект", max_length=50),
        ),
        migrations.AlterField(
            model_name="objectclass",
            name="topic",
            field=models.CharField(
                default="tns1:VideoAnalytics/Model/ObjectClass", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotconfiguration",
            name="name",
            field=models.CharField(default="My token", max_length=255),
        ),
        migrations.AlterField(
            model_name="telegrambotconfiguration",
            name="token",
            field=models.CharField(
                default="7199457381:AAEEqng7z1b8qWrJxR-0Pu0Ye5ywJL0zUos", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="telegramchatid",
            name="chat",
            field=models.BigIntegerField(default=38910803),
        ),
    ]
