# Generated by Django 4.2.5 on 2024-10-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_configurations", "0007_alter_objectclass_name_object_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="location_rtspsrc",
            field=models.CharField(
                default="rtsp://admin:admin@ip/profile2/media.smp", max_length=150
            ),
        ),
    ]
