# Generated by Django 4.2.5 on 2024-10-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_configurations", "0008_alter_camera_location_rtspsrc"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="time_offset",
            field=models.FloatField(default=-1),
        ),
    ]
