# Generated by Django 4.2.5 on 2024-10-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extra_values", "0002_rename_detectclasses_detectclass"),
        ("admin_configurations", "0009_configuration_time_offset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modeldetect",
            name="detect_classes",
            field=models.ManyToManyField(
                db_table="model_descriptor_classes",
                related_name="models",
                to="extra_values.detectclass",
            ),
        ),
    ]
