name: "gfront"

networks:
  private:

services:
  frontend:
    image: antuanuran/api
    restart: unless-stopped
    environment:
      DB_PATH: /app/db/db.sqlite3
      IMAGES_ROOT_FOLDER: /app/data
      CORS_ALLOWED_ORIGINS: http://localhost:5500
    networks:
      - private
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./db:/app/db
      - ../data:/app/data

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - private
    depends_on:
      - frontend
    volumes:
      - ./static:/var/static
      - ./media:/var/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
