### 1. GET.
GET http://91.197.96.129/api/name-profiles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic


### 2. POST.
POST http://91.197.96.129/api/name-profiles/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic
Content-Type: application/json

{
  "name": "h264-666"
}


###3. PATCH. Изменение  (по id)
PATCH http://91.197.96.129/api/name-profiles/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic
Content-Type: application/json

{
  "name": "h264-777"
}


### 4. DELETE. Удаление  (по id)
DELETE http://91.197.96.129/api/name-profiles/5/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic

