### 1. GET.
GET http://91.197.96.129/api/name-videofiles/
Authorization: Bearer {{token}}


### 2. POST.
POST http://91.197.96.129/api/name-videofiles/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "krasava.mp4"
}


###3. PATCH. Изменение  (по id)
PATCH http://91.197.96.129/api/name-videofiles/8/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "krasava2.mp4"
}


### 4. DELETE. Удаление  (по id)
DELETE http://91.197.96.129/api/name-videofiles/8/
Authorization: Bearer {{token}}

