### 1. GET
GET http://91.197.96.129/api/models/
Authorization: Bearer {{token}}


### 2. POST
POST http://91.197.96.129/api/models/
Authorization: Bearer {{token}}
Content-Type: application/json

{
      "name_model": "human_fault",
      "path": "/app/models/pt/human.pt",
      "conf": 0.66,
      "type": "model_pose_yolo",
      "task": "pose",
      "detect_classes": [1, 2, 3, 4, 5]
}


### 3. PATCH
PATCH http://91.197.96.129/api/models/8/
Authorization: Bearer {{token}}
Content-Type: application/json

{
      "detect_classes": [1, 2, 3, 4]
}


### 4. DELETE
DELETE http://91.197.96.129/api/models/8/
Authorization: Bearer {{token}}

