### 1. GET
GET http://91.197.96.129/api/telegram/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic


### 2. POST
POST http://91.197.96.129/api/telegram/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic
Content-Type: application/json

{
    "name": "token",
    "token": "7199457381:AAEEqng7z1b8qWrJxR-0Pu0Ye5ywJL0zUos"
}


### 3. PATCH
PATCH http://91.197.96.129/api/telegram/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic
Content-Type: application/json

{
    "name": "token_77777"
}


### 4. DELETE
DELETE http://91.197.96.129/api/telegram/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic

###***********************************************************************************
###CHATS IDS


### 1. GET
GET http://91.197.96.129/api/tg-chats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic


### 2. POST
POST http://localhost/api/tg-chats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic
Content-Type: application/json

{
  "config_id":  2,
  "chat": "38910803"
}


### 3. PATCH
PATCH http://localhost/api/tg-chats/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic
Content-Type: application/json

{
  "chat": "38910803"
}


### 4. DELETE
DELETE http://localhost/api/tg-chats/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxNjU3ODEyLCJpYXQiOjE3MzAxMjE4MTIsImp0aSI6IjA2MWM0NTY5N2M3MzRlMTFiYTZkNDQxZjE2ODQ2ZjNiIiwidXNlcl9pZCI6Mn0.yDoqBfRYi18Vakjmgv7jqgOyXJ_dwLg8EcdO14yFkic
