name: "gfront"

networks:
  private:

volumes:
  pg_data:

services:
  backend:
    container_name: front_back
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - private
#    volumes:
#      - ../backend/admin_configurations/configs:/app/configs/common/
#      - ../backend/metadata_processor/configs:/app/configs/time_between_savings/
#      - ../backend/onvif/configs:/app/configs/onvif/
#      - ../backend/telegram/configs:/app/configs/telegram/
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ../:/project
#    ports:
#      - "8000:8000"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - private
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
