# Generated by Django 4.2.5 on 2024-10-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_configurations", "0009_configuration_time_offset"),
        ("extra_values", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DetectClasses",
            new_name="DetectClass",
        ),
    ]
